workflows:
  android-release:
    name: Android Release Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: 3.22.3
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf .dart_tool
          rm -rf build
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build AAB
        script: |
          flutter build appbundle --release --verbose
    artifacts:
      - build/**/outputs/bundle/**/*.aab
    publishing:
      email:
        recipients:
          - your_email@example.com  # Replace with your email