name: Build Android AAB

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'  # Specify the Java distribution

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build AAB
      run: flutter build appbundle --release --verbose

    - name: Verify AAB exists
      run: ls -la build/app/outputs/bundle/release/

    - name: Upload AAB
      uses: actions/upload-artifact@v4
      with:
        name: appbundle
        path: build/app/outputs/bundle/release/app-release.aab
